# Generated by Django 3.0.5 on 2020-04-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleMail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetails',
            new_name='ContactDetail',
        ),
    ]
